version: "3.9"
services:
  app:
    build: .
    container_name: todo-app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: tasksuser
      DB_PASSWORD: taskspassword
      DB_NAME: tasksdb
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: tasksdb
      MYSQL_USER: tasksuser
      MYSQL_PASSWORD: taskspassword
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
